### ISSUE TITLE
Allow timeout configuration

### ISSUE THREAD

**Issue by TisButMe** [sschneider1207/ExCloudinary#5]
Hey,

In our use case, we're upload pretty big pictures, which may take >5s to be uploaded, which means we need a higher timeout. HTTPoison supports higher timeouts (https://github.com/edgurgel/httpoison/blob/master/lib/httpoison/base.ex#L128), but we can't set them using excloudinary.

Would you merge a PR that allowed users of excloudinary to set timeouts in `upload_image` ?

Thanks,
Thomas

**Comment by jschneider1207** [comment]
Not sure why I didn't include it to begin with, but I just added it and pushed version 0.2.2 to hex.  All the API calls in the `ExCloudinary` module now take an optional `timeout` value in ms as the last argument.  It's default value is 5000 (5 seconds).  I used 5 seconds because it's a standard timeout value with erlang/elixir (see genservers and such)

**Comment by TisButMe** [comment]
Thanks!
